default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ''
#  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: muraQiita2_development

test:
  <<: *default
  database: muraQiita2_test

production:
  <<: *default
  database: muraQiita2_production

