# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4603246671b7110cd339c2c465d3c2a8033e18b7cc8da7712caab545db352f72f863e33da29847d2eb84c5d63c7a0f5c4e3dea2b903a984d17e85fba5fd453ef

test:
  secret_key_base: 88e443e7c8e307bc6ebdcd93519550b1ab35060a23571c88a17fd799dd49ef5cab81f5efce905cffa4998bd64feb7176965dae637b4459715e9764b1df1882db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
